### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by kloworizer** [zillionare/python-project-wizard#33]
* Date you used Cookiecutter PyPackage:
* Cookiecutter version used, if any:
* Python version, if any:
* Operating System:

### Description

ModuleNotFoundError: No module named 'pkg_resources'

### What I Did

```
Paste the command(s) you ran and the output.
```

**Comment by zillionare** [comment]
Hi @kloworizer , would you please kindly share reproducing steps? Was this happens when you run ppw, or when you build your own artifact?

**Comment by zillionare** [comment]
fixed in v1.3.5
